package com.adhithimaran.cultivate.data.repository

import com.adhithimaran.cultivate.data.model.Completion
import com.adhithimaran.cultivate.data.model.Habit
import com.adhithimaran.cultivate.data.model.HabitType
import com.google.firebase.Timestamp
import com.google.firebase.auth.FirebaseAuth
import com.google.firebase.firestore.FirebaseFirestore
import kotlinx.coroutines.channels.awaitClose
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.callbackFlow
import kotlinx.coroutines.tasks.await

/**
 * HabitRepository is the single source of truth for all Firestore data operations.
 * All habit and completion reads/writes go through this class — no other part of the
 * app should talk to Firestore directly.
 *
 * Data is scoped per user: every path is nested under `users/{uid}/` so that
 * Firestore security rules can guarantee users only access their own data.
 */
class HabitRepository {

    private val db   = FirebaseFirestore.getInstance()
    private val auth = FirebaseAuth.getInstance()

    /**
     * Builds and returns a Firestore reference pointing to the current user's
     * `habits` subcollection: `users/{uid}/habits`.
     *
     * Declared as a function (not a val) so that [auth.currentUser] is re-evaluated
     * on every call, correctly reflecting any auth state changes (e.g. sign-out/sign-in).
     *
     * @throws NullPointerException if called while no user is signed in.
     * @return A [CollectionReference] for the current user's habits.
     */
    private fun userHabitsRef() = db
        .collection("users")
        .document(auth.currentUser!!.uid)
        .collection("habits")

    /**
     * Builds and returns a Firestore reference pointing to the current user's
     * `completions` subcollection: `users/{uid}/completions`.
     *
     * Declared as a function (not a val) so that [auth.currentUser] is re-evaluated
     * on every call, correctly reflecting any auth state changes (e.g. sign-out/sign-in).
     *
     * @throws NullPointerException if called while no user is signed in.
     * @return A [CollectionReference] for the current user's completions.
     */
    private fun userCompletionsRef() = db
        .collection("users")
        .document(auth.currentUser!!.uid)
        .collection("completions")

    // ── Habit operations ──────────────────────────────────────────────────────

    /**
     * Writes a new habit document to Firestore under the current user's `habits` collection.
     * The document ID is auto-generated by Firestore, then injected into the habit before saving
     * so that the stored document's `id` field matches its own document ID.
     *
     * @param habit The [Habit] to save. The `id` field on the passed-in object is ignored
     *              and replaced with the Firestore-generated ID.
     * @return The auto-generated Firestore document ID of the newly created habit.
     */
    suspend fun addHabit(habit: Habit): String {
        val docRef = userHabitsRef().document()
        val withId = habit.copy(id = docRef.id)
        docRef.set(withId.toMap()).await()
        return docRef.id
    }

    /**
     * Returns a real-time [Flow] that emits the current user's full habit list whenever
     * the Firestore `habits` collection changes (add, update, or delete).
     *
     * @return A [Flow] that emits a [List<Habit>] every time the habits collection changes.
     *         Emits an empty list if the collection is empty.
     */
    fun getHabitsFlow(): Flow<List<Habit>> = callbackFlow {
        val listener = userHabitsRef()
            .addSnapshotListener { snapshot, error ->
                if (error != null) { close(error); return@addSnapshotListener }
                val habits = snapshot?.documents?.mapNotNull { doc ->
                    doc.data?.let { Habit.fromMap(it) }
                } ?: emptyList()
                trySend(habits)
            }
        awaitClose { listener.remove() }
    }

    /**
     * Returns a real-time [Flow] for a single habit document.
     *
     * Used by the Detail screen so it subscribes to exactly one document rather
     * than downloading the entire habits collection. Emits null if the document
     * is deleted while the screen is open (the screen can then navigate back).
     *
     * @param habitId The Firestore document ID of the habit to observe.
     */
    fun getHabitFlow(habitId: String): Flow<Habit?> = callbackFlow {
        val listener = userHabitsRef()
            .document(habitId)
            .addSnapshotListener { snapshot, error ->
                if (error != null) { close(error); return@addSnapshotListener }
                val habit = snapshot?.data?.let { Habit.fromMap(it) }
                trySend(habit)
            }
        awaitClose { listener.remove() }
    }

    /**
     * Permanently deletes a habit document from Firestore by its ID.
     *
     * Note: This does not delete associated completions. If you need to clean those up
     * too, you would need to query and delete them separately.
     *
     * @param habitId The Firestore document ID of the habit to delete.
     */
    suspend fun deleteHabit(habitId: String) {
        userHabitsRef().document(habitId).delete().await()
    }

    /**
     * Overwrites an existing habit document in Firestore with the new field values.
     *
     * @param habit The [Habit] containing updated values. Its `id` must match an
     *              existing document — if it doesn't, a new document will be created.
     */
    suspend fun updateHabit(habit: Habit) {
        userHabitsRef().document(habit.id).set(habit.toMap()).await()
    }

    // ── Completion operations ─────────────────────────────────────────────────

    /**
     * Logs a new completion event for a given habit.
     *
     * @param habitId The ID of the habit being marked as complete.
     * @param type The [HabitType] of the habit, stored for easier querying later.
     * @return The auto-generated Firestore document ID of the new completion record.
     */
    suspend fun addCompletion(habitId: String, type: HabitType): String {
        val docRef = userCompletionsRef().document()
        val completion = Completion(
            id          = docRef.id,
            habitId     = habitId,
            completedAt = Timestamp.now(),
            type        = type
        )
        docRef.set(completion.toMap()).await()
        return docRef.id
    }

    /**
     * Returns a real-time [Flow] of ALL completion records for the current user.
     *
     * The Home screen ViewModel uses this instead of per-habit queries so it can
     * combine habits + completions in a single [kotlinx.coroutines.flow.combine] call,
     * computing streaks and completion state entirely in memory — no N separate
     * Firestore listeners needed.
     *
     * @return A [Flow] that emits a [List<Completion>] whenever any completion changes.
     */
    fun getAllCompletionsFlow(): Flow<List<Completion>> = callbackFlow {
        val listener = userCompletionsRef()
            .addSnapshotListener { snapshot, error ->
                if (error != null) { close(error); return@addSnapshotListener }
                val completions = snapshot?.documents?.mapNotNull { doc ->
                    doc.data?.let { Completion.fromMap(it) }
                } ?: emptyList()
                trySend(completions)
            }
        awaitClose { listener.remove() }
    }

    /**
     * Returns a real-time [Flow] that emits completion records for a specific habit only.
     * Prefer [getAllCompletionsFlow] when you need data for multiple habits at once.
     *
     * @param habitId The ID of the habit whose completions should be streamed.
     */
    fun getCompletionsForHabit(habitId: String): Flow<List<Completion>> = callbackFlow {
        val listener = userCompletionsRef()
            .whereEqualTo("habitId", habitId)
            .addSnapshotListener { snapshot, error ->
                if (error != null) { close(error); return@addSnapshotListener }
                val completions = snapshot?.documents?.mapNotNull { doc ->
                    doc.data?.let { Completion.fromMap(it) }
                } ?: emptyList()
                trySend(completions)
            }
        awaitClose { listener.remove() }
    }
}